name: Tag & Build

on:
    push:
        branches: [ main ]

jobs:
    tag-build:
        name: Tag & Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Configuring Git
              run: |
                  git config --global user.email "me@dunklestoast.de"
                  git config --global user.name "lerna"
            - name: Versioning via lerna
              run: npx lerna version
            - name: Installing Dependencies
              run: npx lerna bootstrap
            - name: Building all the things
              run: npx lerna run build
